### ISSUE TITLE
Changing animation style

### ISSUE THREAD

**Issue by petrenkorf** [fayaz07/animated_splash#18]
Amazing Project!

There is just one animation in the package? If not, how do I specify which animation I will use?

**Comment by fayaz07** [comment]
Yeah, it supports other animations too, but I didn't get to test those. Feel free to try from the example project.

**Comment by petrenkorf** [comment]
@fayaz07 I'm trying to use the example, but a I'm getting the following error:

ib/main.dart:22:7: Error: No named parameter with the name 'style'.    
      style: AnimationStyle.Still,                                      
      ^^^^^                                                             
/home/ptrs/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/animat
ed_splash-1.0.0/lib/animated_splash.dart:17:3: Context: Found this candidate,
but the arguments don't match.
  AnimatedSplash(                                                       
  ^^^^^^^^^^^^^^                                                        
lib/main.dart:41:7: Error: No named parameter with the name 'style'.    
      style: AnimationStyle.FadeIn,                                     
      ^^^^^                                                             
/home/ptrs/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/animat
ed_splash-1.0.0/lib/animated_splash.dart:17:3: Context: Found this candidate,
but the arguments don't match.
  AnimatedSplash(                                                       
  ^^^^^^^^^^^^^^                                                        
lib/main.dart:54:7: Error: No named parameter with the name 'style'.    
      style: AnimationStyle.FadeIn,                                     
      ^^^^^                                                             
/home/ptrs/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/animat
ed_splash-1.0.0/lib/animated_splash.dart:17:3: Context: Found this candidate,
but the arguments don't match.
  AnimatedSplash(                                                       
  ^^^^^^^^^^^^^^

**Comment by fayaz07** [comment]
There maybe few issues, I didn't completely test it, please check the
source code

Thanks
