### ISSUE TITLE
Image Size Problem

### ISSUE THREAD

**Issue by AreebaJawed** [fayaz07/animated_splash#19]
I wan my image in AnimatedSplash to fit full screen.
How can I do that?

AnimatedSplash(
      imagePath: 'assets/ss.gif',
      customFunction: playSound,
      duration: 4000,
      home: SecondScreen(),
      outputAndHome: output,
      type: AnimatedSplashType.BackgroundProcess,
    ),

**Comment by fayaz07** [comment]
custom child can solve the issue
